[theme]
base = "light"
primaryColor = "#7C3AED"
backgroundColor = "#EEF2FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"
borderColor = "#E2E8F0"
showWidgetBorder = true
baseRadius = "0.7rem"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[browser]
gatherUsageStats = false
